-- AlterTable
ALTER TABLE `notifications` ADD COLUMN `type` ENUM('FOLLOW', 'FRIEND_REQUEST', 'FRIEND_REQUEST_ACCEPTED', 'FRIEND_ADDED', 'UNFOLLOW', 'BLOG_COMMENT', 'BLOG_COMMENT_REPLY', 'BLOG_REACTION', 'BLOG_PUBLISHED', 'QUIZ_CREATED', 'QUIZ_SHARED', 'QUIZ_RESULT', 'LESSON_COMPLETED', 'MESSAGE_RECEIVED', 'GROUP_MESSAGE', 'ROOM_MESSAGE', 'ROOM_CREATED', 'SYSTEM', 'ANNOUNCEMENT') NOT NULL DEFAULT 'SYSTEM';

-- CreateIndex
CREATE INDEX `notifications_type_idx` ON `notifications`(`type`);
