-- AlterTable
ALTER TABLE `users` ADD COLUMN `isOnline` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `isTyping` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `lastOnline` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
