-- AlterTable
ALTER TABLE `achievements` MODIFY `type` ENUM('FIRST_FRIEND', 'FRIEND_MASTER', 'SOCIAL_BUTTERFLY', 'FIRST_LESSON', 'LEARNING_STREAK_7', 'LEARNING_STREAK_30', 'POLYGLOT', 'LANGUAGE_EXPERT', 'FIRST_QUIZ', 'QUIZ_MASTER', 'QUIZ_WIZARD', 'PERFECT_SCORE', 'FIRST_BLOG', 'BLOGGER', 'VIRAL_POST', 'COMMENTATOR', 'EARLY_BIRD', 'COMMUNITY_HELPER', 'CONTENT_CREATOR', 'LEGENDARY') NOT NULL;
