async function seedAchievements(prisma, admin, users) {
  const achievementSeeds = [
    {
      userId: admin.id,
      type: "FIRST_BLOG",
      title: "Blogger Pemula",
      description: "Mempublikasikan blog pertama",
      icon: "✍️",
      badgeColor: "blue",
      points: 10,
    },
    {
      userId: admin.id,
      type: "BLOGGER",
      title: "Blogger Aktif",
      description: "Mempublikasikan 5 blog post",
      icon: "📝",
      badgeColor: "orange",
      points: 50,
    },
    {
      userId: admin.id,
      type: "COMMUNITY_HELPER",
      title: "Pembantu Komunitas",
      description: "Membantu 10 orang (reaksi/komentar)",
      icon: "🤝",
      badgeColor: "green",
      points: 100,
    },
    {
      userId: admin.id,
      type: "ROOM_CREATOR",
      title: "Pembuka Ruang",
      description: "Membuat room diskusi pertama",
      icon: "🏠",
      badgeColor: "cyan",
      points: 20,
    },
    {
      userId: admin.id,
      type: "ROOM_HOST",
      title: "Tuan Rumah Komunitas",
      description: "Membuat 3 room diskusi",
      icon: "🗣️",
      badgeColor: "blue",
      points: 75,
    },
    {
      userId: admin.id,
      type: "DM_STARTER",
      title: "Pembuka Obrolan",
      description: "Mengirim pesan pribadi pertama",
      icon: "💌",
      badgeColor: "pink",
      points: 20,
    },
    {
      userId: users[0].id,
      type: "FIRST_LESSON",
      title: "Pelajaran Pertama",
      description: "Menyelesaikan pelajaran pertama",
      icon: "📚",
      badgeColor: "green",
      points: 10,
    },
    {
      userId: users[0].id,
      type: "FIRST_FRIEND",
      title: "Teman Pertama",
      description: "Menambahkan teman pertama Anda",
      icon: "👥",
      badgeColor: "blue",
      points: 10,
    },
    {
      userId: users[1].id,
      type: "FIRST_FRIEND",
      title: "Teman Pertama",
      description: "Menambahkan teman pertama Anda",
      icon: "👥",
      badgeColor: "blue",
      points: 10,
    },
    {
      userId: users[0].id,
      type: "FIRST_QUIZ",
      title: "Kuis Pertama",
      description: "Menyelesaikan kuis pertama",
      icon: "❓",
      badgeColor: "blue",
      points: 10,
    },
    {
      userId: users[0].id,
      type: "PERFECT_SCORE",
      title: "Skor Sempurna",
      description: "Mendapatkan skor sempurna (100%) pada kuis",
      icon: "💯",
      badgeColor: "red",
      points: 50,
    },
    {
      userId: users[0].id,
      type: "QUIZ_MASTER",
      title: "Master Kuis",
      description: "Mendapatkan skor sempurna di 5 kuis",
      icon: "🏆",
      badgeColor: "gold",
      points: 100,
    },
    {
      userId: users[1].id,
      type: "FIRST_LESSON",
      title: "Pelajaran Pertama",
      description: "Menyelesaikan pelajaran pertama",
      icon: "📚",
      badgeColor: "green",
      points: 10,
    },
    {
      userId: users[1].id,
      type: "FIRST_QUIZ",
      title: "Kuis Pertama",
      description: "Menyelesaikan kuis pertama",
      icon: "❓",
      badgeColor: "blue",
      points: 10,
    },
    {
      userId: users[2].id,
      type: "FIRST_LESSON",
      title: "Pelajaran Pertama",
      description: "Menyelesaikan pelajaran pertama",
      icon: "📚",
      badgeColor: "green",
      points: 10,
    },
    {
      userId: users[2].id,
      type: "FIRST_QUIZ",
      title: "Kuis Pertama",
      description: "Menyelesaikan kuis pertama",
      icon: "❓",
      badgeColor: "blue",
      points: 10,
    },
    {
      userId: users[3].id,
      type: "FIRST_LESSON",
      title: "Pelajaran Pertama",
      description: "Menyelesaikan pelajaran pertama",
      icon: "📚",
      badgeColor: "green",
      points: 10,
    },
    {
      userId: users[3].id,
      type: "FIRST_QUIZ",
      title: "Kuis Pertama",
      description: "Menyelesaikan kuis pertama",
      icon: "❓",
      badgeColor: "blue",
      points: 10,
    },
    {
      userId: users[4].id,
      type: "FIRST_LESSON",
      title: "Pelajaran Pertama",
      description: "Menyelesaikan pelajaran pertama",
      icon: "📚",
      badgeColor: "green",
      points: 10,
    },
    {
      userId: users[4].id,
      type: "FIRST_QUIZ",
      title: "Kuis Pertama",
      description: "Menyelesaikan kuis pertama",
      icon: "❓",
      badgeColor: "blue",
      points: 10,
    },
    {
      userId: users[0].id,
      type: "COMMENTATOR",
      title: "Komentator",
      description: "Meninggalkan 50 komentar",
      icon: "💬",
      badgeColor: "green",
      points: 50,
    },
    {
      userId: users[0].id,
      type: "COMMUNITY_HELPER",
      title: "Pembantu Komunitas",
      description: "Membantu 10 orang (reaksi/komentar)",
      icon: "🤝",
      badgeColor: "green",
      points: 100,
    },
    {
      userId: users[0].id,
      type: "CONTENT_CREATOR",
      title: "Pembuat Konten",
      description: "Membuat konten di 3+ fitur berbeda",
      icon: "🎨",
      badgeColor: "purple",
      points: 75,
    },
    {
      userId: users[0].id,
      type: "SOCIAL_BUTTERFLY",
      title: "Kupu-kupu Sosial",
      description: "Memiliki 50+ pengikut",
      icon: "🦋",
      badgeColor: "pink",
      points: 100,
    },
    {
      userId: users[1].id,
      type: "ROOM_CREATOR",
      title: "Pembuka Ruang",
      description: "Membuat room diskusi pertama",
      icon: "🏠",
      badgeColor: "cyan",
      points: 20,
    },
    {
      userId: users[1].id,
      type: "DM_STARTER",
      title: "Pembuka Obrolan",
      description: "Mengirim pesan pribadi pertama",
      icon: "💌",
      badgeColor: "pink",
      points: 20,
    },
    {
      userId: users[1].id,
      type: "EARLY_BIRD",
      title: "Burung Pagi",
      description: "Bergabung dengan ruang diskusi pertama",
      icon: "🐦",
      badgeColor: "yellow",
      points: 10,
    },
    {
      userId: users[2].id,
      type: "ROOM_HOST",
      title: "Tuan Rumah Komunitas",
      description: "Membuat 3 room diskusi",
      icon: "🗣️",
      badgeColor: "blue",
      points: 75,
    },
    {
      userId: users[2].id,
      type: "COMMUNITY_VOICE",
      title: "Suara Komunitas",
      description: "Mengirim 25 pesan di room diskusi",
      icon: "📢",
      badgeColor: "emerald",
      points: 75,
    },
    {
      userId: users[3].id,
      type: "QUIZ_MASTER",
      title: "Master Kuis",
      description: "Mendapatkan skor sempurna di 5 kuis",
      icon: "🏆",
      badgeColor: "gold",
      points: 100,
    },
    {
      userId: users[3].id,
      type: "PERFECT_SCORE",
      title: "Skor Sempurna",
      description: "Mendapatkan skor sempurna (100%) pada kuis",
      icon: "💯",
      badgeColor: "red",
      points: 50,
    },
    {
      userId: users[4].id,
      type: "BLOGGER",
      title: "Blogger Aktif",
      description: "Mempublikasikan 5 blog post",
      icon: "📝",
      badgeColor: "orange",
      points: 50,
    },
    {
      userId: users[4].id,
      type: "VIRAL_POST",
      title: "Viral!",
      description: "Mendapatkan 100+ reaksi pada sebuah postingan",
      icon: "🚀",
      badgeColor: "red",
      points: 100,
    },
  ];

  for (const achievement of achievementSeeds) {
    await prisma.achievement.upsert({
      where: {
        userId_type: {
          userId: achievement.userId,
          type: achievement.type,
        },
      },
      update: {
        title: achievement.title,
        description: achievement.description,
        icon: achievement.icon,
        badgeColor: achievement.badgeColor,
        points: achievement.points,
      },
      create: achievement,
    });
  }

  console.log(`✅ ${achievementSeeds.length} achievements seeded`);
  return achievementSeeds.length;
}

module.exports = { seedAchievements };
