async function seedGrammar(prisma) {
  const GrammarData = [
    {
      level: "A1",
      sentence: "They is happy at home.",
      words: ["They", "is", "happy", "at", "home"],
      wrongIndex: 1,
      choices: ["are", "am", "is", "be"],
      answer: "are",
    },
    {
      level: "A1",
      sentence: "He have a small dog.",
      words: ["He", "have", "a", "small", "dog"],
      wrongIndex: 1,
      choices: ["has", "have", "had", "having"],
      answer: "has",
    },
    {
      level: "A1",
      sentence: "I does my homework now.",
      words: ["I", "does", "my", "homework", "now"],
      wrongIndex: 1,
      choices: ["do", "does", "did", "doing"],
      answer: "do",
    },
    {
      level: "A1",
      sentence: "We likes to play football.",
      words: ["We", "likes", "to", "play", "football"],
      wrongIndex: 1,
      choices: ["like", "likes", "liked", "liking"],
      answer: "like",
    },
    {
      level: "A1",
      sentence: "My brother play the piano.",
      words: ["My", "brother", "play", "the", "piano"],
      wrongIndex: 2,
      choices: ["play", "plays", "played", "playing"],
      answer: "plays",
    },
    {
      level: "A1",
      sentence: "The cat drink the milk.",
      words: ["The", "cat", "drink", "the", "milk"],
      wrongIndex: 2,
      choices: ["drink", "drinks", "drank", "drinking"],
      answer: "drinks",
    },
    {
      level: "A1",
      sentence: "She are a smart student.",
      words: ["She", "are", "a", "smart", "student"],
      wrongIndex: 1,
      choices: ["is", "are", "am", "be"],
      answer: "is",
    },
    {
      level: "A1",
      sentence: "You has a blue bike.",
      words: ["You", "has", "a", "blue", "bike"],
      wrongIndex: 1,
      choices: ["have", "has", "had", "having"],
      answer: "have",
    },
    {
      level: "A1",
      sentence: "He do not like fish.",
      words: ["He", "do", "not", "like", "fish"],
      wrongIndex: 1,
      choices: ["do", "does", "did", "doing"],
      answer: "does",
    },
    {
      level: "A1",
      sentence: "It am a hot day.",
      words: ["It", "am", "a", "hot", "day"],
      wrongIndex: 1,
      choices: ["is", "am", "are", "be"],
      answer: "is",
    },
    {
      level: "A1",
      sentence: "They eats apples for lunch.",
      words: ["They", "eats", "apples", "for", "lunch"],
      wrongIndex: 1,
      choices: ["eat", "eats", "ate", "eating"],
      answer: "eat",
    },
    {
      level: "A1",
      sentence: "I is a new teacher.",
      words: ["I", "is", "a", "new ", "teacher"],
      wrongIndex: 1,
      choices: ["am", "is", "are", "be"],
      answer: "am",
    },
    {
      level: "A1",
      sentence: "We has two big houses.",
      words: ["We", "has", "two", "big", "houses"],
      wrongIndex: 1,
      choices: ["have", "has", "had", "having"],
      answer: "have",
    },
    {
      level: "A1",
      sentence: "She read books every night.",
      words: ["She", "read", "books", "every", "night"],
      wrongIndex: 1,
      choices: ["reads", "read", "reading", "readed"],
      answer: "reads",
    },
    {
      level: "A1",
      sentence: "My father work in office.",
      words: ["My", "father", "work", "in ", "office"],
      wrongIndex: 2,
      choices: ["work", "works", "worked", "working"],
      answer: "works",
    },
    {
      level: "A1",
      sentence: "The dogs runs in garden.",
      words: ["The", "dogs", "runs", "in", "garden"],
      wrongIndex: 2,
      choices: ["run", "runs", "ran", "running"],
      answer: "run",
    },
    {
      level: "A1",
      sentence: "He go to the park.",
      words: ["He", "go", "to", "the", "park"],
      wrongIndex: 1,
      choices: ["goes", "go", "gone", "going"],
      answer: "goes",
    },
    {
      level: "A1",
      sentence: "You is a good friend.",
      words: ["You", "is", "a", "good", "friend"],
      wrongIndex: 1,
      choices: ["are", "is", "am", "be"],
      answer: "are",
    },
    {
      level: "A1",
      sentence: "They has a pet rabbit.",
      words: ["They", "has", "a", "pet", "rabbit"],
      wrongIndex: 1,
      choices: ["have", "has", "had", "having"],
      answer: "have",
    },
    {
      level: "A1",
      sentence: "She do her homework well.",
      words: ["She", "do", "her", "homework", "well"],
      wrongIndex: 1,
      choices: ["does", "do", "did", "doing"],
      answer: "does",
    },
    {
      level: "A1",
      sentence: "I likes to eat bread.",
      words: ["I", "likes", "to", "eat", "bread"],
      wrongIndex: 1,
      choices: ["like", "likes", "liked", "liking"],
      answer: "like",
    },
    {
      level: "A1",
      sentence: "We is at the store.",
      words: ["We", "is", "at", "the", "store"],
      wrongIndex: 1,
      choices: ["are", "is", "am", "be"],
      answer: "are",
    },
    {
      level: "A1",
      sentence: "He drink water after sports.",
      words: ["He", "drink", "water", "after", "sports"],
      wrongIndex: 1,
      choices: ["drinks", "drink", "drank", "drinking"],
      answer: "drinks",
    },
    {
      level: "A1",
      sentence: "The bird fly very high.",
      words: ["The", "bird", "fly", "very", "high"],
      wrongIndex: 2,
      choices: ["flies", "fly", "flown", "flying"],
      answer: "flies",
    },
    {
      level: "A1",
      sentence: "It have a long tail.",
      words: ["It", "have", "a", "long", "tail"],
      wrongIndex: 1,
      choices: ["has", "have", "had", "having"],
      answer: "has",
    },
    {
      level: "A1",
      sentence: "You does read many books.",
      words: ["You", "does", "read", "many", "books"],
      wrongIndex: 1,
      choices: ["do", "does", "did", "doing"],
      answer: "do",
    },
    {
      level: "A1",
      sentence: "They is playing outside now.",
      words: ["They", "is", "playing", "outside", "now"],
      wrongIndex: 1,
      choices: ["are", "is", "am", "be"],
      answer: "are",
    },
    {
      level: "A1",
      sentence: "She study English at school.",
      words: ["She", "study", "English", "at", "school"],
      wrongIndex: 1,
      choices: ["studies", "study", "studying", "studied"],
      answer: "studies",
    },
    {
      level: "A1",
      sentence: "My friend are very tall.",
      words: ["My", "friend", "are", "very", "tall"],
      wrongIndex: 2,
      choices: ["is", "are", "am", "be"],
      answer: "is",
    },
    {
      level: "A1",
      sentence: "We has breakfast at seven.",
      words: ["We", "has", "breakfast", "at", "seven"],
      wrongIndex: 1,
      choices: ["have", "has", "had", "having"],
      answer: "have",
    },
    {
      level: "A1",
      sentence: "He run fast every morning.",
      words: ["He", "run", "fast", "every", "morning"],
      wrongIndex: 1,
      choices: ["runs", "run", "ran", "running"],
      answer: "runs",
    },
    {
      level: "A1",
      sentence: "The child play with toys.",
      words: ["The", "child", "play", "with", "toys"],
      wrongIndex: 2,
      choices: ["plays", "play", "played", "playing"],
      answer: "plays",
    },
    {
      level: "A1",
      sentence: "I is reading a book.",
      words: ["I", "is", "reading", "a", "book"],
      wrongIndex: 1,
      choices: ["am", "is", "are", "be"],
      answer: "am",
    },
    {
      level: "A1",
      sentence: "They does not like milk.",
      words: ["They", "does", "not", "like", "milk"],
      wrongIndex: 1,
      choices: ["do", "does", "did", "doing"],
      answer: "do",
    },
    {
      level: "A1",
      sentence: "She have a new phone.",
      words: ["She", "have", "a", "new", "phone"],
      wrongIndex: 1,
      choices: ["has", "have", "had", "having"],
      answer: "has",
    },
    {
      level: "A1",
      sentence: "We loves to watch movies.",
      words: ["We", "loves", "to", "watch", "movies"],
      wrongIndex: 1,
      choices: ["love", "loves", "loved", "loving"],
      answer: "love",
    },
    {
      level: "A1",
      sentence: "He are a famous doctor.",
      words: ["He", "are", "a", "famous", "doctor"],
      wrongIndex: 1,
      choices: ["is", "are", "am", "be"],
      answer: "is",
    },
    {
      level: "A1",
      sentence: "The teacher explain the lesson.",
      words: ["The", "teacher", "explain", "the", "lesson"],
      wrongIndex: 2,
      choices: ["explains", "explain", "explained", "explaining"],
      answer: "explains",
    },
    {
      level: "A1",
      sentence: "They eats dinner at home.",
      words: ["They", "eats", "dinner", "at", "home"],
      wrongIndex: 1,
      choices: ["eat", "eats", "ate", "eating"],
      answer: "eat",
    },
    {
      level: "A1",
      sentence: "I has a big family.",
      words: ["I", "has", "a", "big", "family"],
      wrongIndex: 1,
      choices: ["have", "has", "had", "having"],
      answer: "have",
    },
    {
      level: "A1",
      sentence: "She do Yoga every week.",
      words: ["She", "do", "Yoga", "every", "week"],
      wrongIndex: 1,
      choices: ["does", "do", "did", "doing"],
      answer: "does",
    },
    {
      level: "A1",
      sentence: "You is late for class.",
      words: ["You", "is", "late", "for", "class"],
      wrongIndex: 1,
      choices: ["are", "is", "am", "be"],
      answer: "are",
    },
    {
      level: "A1",
      sentence: "He sing well on stage.",
      words: ["He", "sing", "well", "on", "stage"],
      wrongIndex: 1,
      choices: ["sings", "sing", "sang", "singing"],
      answer: "sings",
    },
    {
      level: "A1",
      sentence: "We likes fresh fruit here.",
      words: ["We", "likes", "fresh", "fruit", "here"],
      wrongIndex: 1,
      choices: ["like", "likes", "liked", "liking"],
      answer: "like",
    },
    {
      level: "A1",
      sentence: "It rain in the morning.",
      words: ["It", "rain", "in", "the", "morning"],
      wrongIndex: 1,
      choices: ["rains", "rain", "rained", "raining"],
      answer: "rains",
    },
    {
      level: "A1",
      sentence: "My cat have soft fur.",
      words: ["My", "cat", "have", "soft", "fur"],
      wrongIndex: 2,
      choices: ["has", "have", "had", "having"],
      answer: "has",
    },
    {
      level: "A1",
      sentence: "They is busy with work.",
      words: ["They", "is", "busy", "with", "work"],
      wrongIndex: 1,
      choices: ["are", "is", "am", "be"],
      answer: "are",
    },
    {
      level: "A1",
      sentence: "She drink tea every day.",
      words: ["She", "drink", "tea", "every", "day"],
      wrongIndex: 1,
      choices: ["drinks", "drink", "drank", "drinking"],
      answer: "drinks",
    },
    {
      level: "A1",
      sentence: "He do his chores fast.",
      words: ["He", "do", "his", "chores", "fast"],
      wrongIndex: 1,
      choices: ["does", "do", "did", "doing"],
      answer: "does",
    },
    {
      level: "A1",
      sentence: "The boys plays at park.",
      words: ["The", "boys", "plays", "at", "park"],
      wrongIndex: 2,
      choices: ["play", "plays", "played", "playing"],
      answer: "play",
    },
    {
      level: "A1",
      sentence: "I is ready to go.",
      words: ["I", "is", "ready", "to", "go"],
      wrongIndex: 1,
      choices: ["am", "is", "are", "be"],
      answer: "am",
    },
    {
      level: "A1",
      sentence: "She have three smart sisters.",
      words: ["She", "have", "three", "smart", "sisters"],
      wrongIndex: 1,
      choices: ["has", "have", "had", "having"],
      answer: "has",
    },
    {
      level: "A1",
      sentence: "We does not know him.",
      words: ["We", "does", "not", "know", "him"],
      wrongIndex: 1,
      choices: ["do", "does", "did", "doing"],
      answer: "do",
    },
    {
      level: "A1",
      sentence: "He are my best friend.",
      words: ["He", "are", "my", "best", "friend"],
      wrongIndex: 1,
      choices: ["is", "are", "am", "be"],
      answer: "is",
    },
    {
      level: "A1",
      sentence: "They has a green car.",
      words: ["They", "has", "a", "green", "car"],
      wrongIndex: 1,
      choices: ["have", "has", "had", "having"],
      answer: "have",
    },
    {
      level: "A1",
      sentence: "She likes to dance well.",
      words: ["She", "likes", "to", "dance", "well"],
      wrongIndex: 1,
      choices: ["likes", "like", "liked", "liking"],
      answer: "likes",
    },
    {
      level: "A1",
      sentence: "It is a cold day.",
      words: ["It", "is", "a", "cold", "day"],
      wrongIndex: 1,
      choices: ["is", "am", "are", "be"],
      answer: "is",
    },
    {
      level: "A1",
      sentence: "My dogs eats dry food.",
      words: ["My", "dogs", "eats", "dry", "food"],
      wrongIndex: 2,
      choices: ["eat", "eats", "ate", "eating"],
      answer: "eat",
    },
    {
      level: "A1",
      sentence: "You has many great books.",
      words: ["You", "has", "many", "great", "books"],
      wrongIndex: 1,
      choices: ["have", "has", "had", "having"],
      answer: "have",
    },
    {
      level: "A1",
      sentence: "He watch movies on Friday.",
      words: ["He", "watch", "movies", "on", "Friday"],
      wrongIndex: 1,
      choices: ["watches", "watch", "watched", "watching"],
      answer: "watches",
    },
    {
      level: "A1",
      sentence: "They is happy to help.",
      words: ["They", "is", "happy", "to", "help"],
      wrongIndex: 1,
      choices: ["are", "is", "am", "be"],
      answer: "are",
    },
    {
      level: "A1",
      sentence: "She work at the bank.",
      words: ["She", "work", "at", "the", "bank"],
      wrongIndex: 1,
      choices: ["works", "work", "worked", "working"],
      answer: "works",
    },
    {
      level: "A1",
      sentence: "I likes to play chess.",
      words: ["I", "likes", "to", "play", "chess"],
      wrongIndex: 1,
      choices: ["like", "likes", "liked", "liking"],
      answer: "like",
    },
    {
      level: "A1",
      sentence: "We am very tired now.",
      words: ["We", "am", "very", "tired", "now"],
      wrongIndex: 1,
      choices: ["are", "am", "is", "be"],
      answer: "are",
    },
    {
      level: "A1",
      sentence: "He have a long name.",
      words: ["He", "have", "a", "long", "name"],
      wrongIndex: 1,
      choices: ["has", "have", "had", "having"],
      answer: "has",
    },
    {
      level: "A1",
      sentence: "The sun shine every day.",
      words: ["The", "sun", "shine", "every", "day"],
      wrongIndex: 2,
      choices: ["shines", "shine", "shone", "shining"],
      answer: "shines",
    },
    {
      level: "A1",
      sentence: "She does his laundry today.",
      words: ["She", "does", "his", "laundry", "today"],
      wrongIndex: 1,
      choices: ["does", "do", "did", "doing"],
      answer: "does",
    },
    {
      level: "A1",
      sentence: "I is happy for you.",
      words: ["I", "is", "happy", "for", "you"],
      wrongIndex: 1,
      choices: ["am", "is", "are", "be"],
      answer: "am",
    },
    {
      level: "A1",
      sentence: "He go to work early.",
      words: ["He", "go", "to", "work", "early"],
      wrongIndex: 1,
      choices: ["goes", "go", "gone", "going"],
      answer: "goes",
    },
    {
      level: "A1",
      sentence: "We loves to cook dinner.",
      words: ["We", "loves", "to", "cook", "dinner"],
      wrongIndex: 1,
      choices: ["love", "loves", "loved", "loving"],
      answer: "love",
    },
    {
      level: "A1",
      sentence: "The horse run very fast.",
      words: ["The", "horse", "run", "very", "fast"],
      wrongIndex: 2,
      choices: ["runs", "run", "ran", "running"],
      answer: "runs",
    },
    {
      level: "A1",
      sentence: "You is my best teacher.",
      words: ["You", "is", "my", "best", "teacher"],
      wrongIndex: 1,
      choices: ["are", "is", "am", "be"],
      answer: "are",
    },
    {
      level: "A1",
      sentence: "She have two cute kittens.",
      words: ["She", "have", "two", "cute", "kittens"],
      wrongIndex: 1,
      choices: ["has", "have", "had", "having"],
      answer: "has",
    },
    {
      level: "A1",
      sentence: "They does not eat meat.",
      words: ["They", "does", "not", "eat", "meat"],
      wrongIndex: 1,
      choices: ["do", "does", "did", "doing"],
      answer: "do",
    },
    {
      level: "A1",
      sentence: "He am good at math.",
      words: ["He", "am", "good", "at", "math"],
      wrongIndex: 1,
      choices: ["is", "am", "are", "be"],
      answer: "is",
    },
    {
      level: "A1",
      sentence: "We has nice new clothes.",
      words: ["We", "has", "nice", "new ", "clothes"],
      wrongIndex: 1,
      choices: ["have", "has", "had", "having"],
      answer: "have",
    },
    {
      level: "A1",
      sentence: "She study hard for exam.",
      words: ["She", "study", "hard", "for", "exam"],
      wrongIndex: 1,
      choices: ["studies", "study", "studying", "studied"],
      answer: "studies",
    },
    {
      level: "A1",
      sentence: "My friend play tennis well.",
      words: ["My", "friend", "play", "tennis", "well"],
      wrongIndex: 2,
      choices: ["plays", "play", "played", "playing"],
      answer: "plays",
    },
    {
      level: "A1",
      sentence: "She go to school every day.",
      words: ["She", "go", "to", "school", "every", "day"],
      wrongIndex: 1,
      choices: ["goes", "go", "going", "gone"],
      answer: "goes",
    },
    {
      level: "A1",
      sentence: "They likes to play soccer together.",
      words: ["They", "likes", "to", "play", "soccer", "together"],
      wrongIndex: 1,
      choices: ["like", "likes", "liking", "liked"],
      answer: "like",
    },
    {
      level: "A1",
      sentence: "He am a very good student.",
      words: ["He", "am", "a", "very", "good", "student"],
      wrongIndex: 1,
      choices: ["is", "am", "are", "be"],
      answer: "is",
    },
    {
      level: "A1",
      sentence: "My brother have a blue bicycle.",
      words: ["My", "brother", "have", "a", "blue", "bicycle"],
      wrongIndex: 2,
      choices: ["has", "have", "having", "had"],
      answer: "has",
    },
    {
      level: "A1",
      sentence: "The dog eat meat every morning.",
      words: ["The", "dog", "eat", "meat", "every", "morning"],
      wrongIndex: 2,
      choices: ["eats", "eat", "eating", "eaten"],
      answer: "eats",
    },
    {
      level: "A1",
      sentence: "I does my homework after dinner.",
      words: ["I", "does", "my", "homework", "after", "dinner"],
      wrongIndex: 1,
      choices: ["do", "does", "doing", "done"],
      answer: "do",
    },
    {
      level: "A1",
      sentence: "We is happy at the park.",
      words: ["We", "is", "happy", "at", "the", "park"],
      wrongIndex: 1,
      choices: ["are", "is", "am", "be"],
      answer: "are",
    },
    {
      level: "A1",
      sentence: "She drink water with her lunch.",
      words: ["She", "drink", "water", "with", "her", "lunch"],
      wrongIndex: 1,
      choices: ["drinks", "drink", "drinking", "drank"],
      answer: "drinks",
    },
    {
      level: "A1",
      sentence: "My cat sleep on the sofa.",
      words: ["My", "cat", "sleep", "on", "the", "sofa"],
      wrongIndex: 2,
      choices: ["sleeps", "sleep", "sleeping", "slept"],
      answer: "sleeps",
    },
    {
      level: "A1",
      sentence: "They plays tennis on Sundays.",
      words: ["They", "plays", "tennis", "on", "Sundays"],
      wrongIndex: 1,
      choices: ["play", "plays", "playing", "played"],
      answer: "play",
    },
    {
      level: "A1",
      sentence: "He work in a big office.",
      words: ["He", "work", "in", "a", "big", "office"],
      wrongIndex: 1,
      choices: ["works", "work", "working", "worked"],
      answer: "works",
    },
    {
      level: "A1",
      sentence: "The books is on the desk.",
      words: ["The", "books", "is", "on", "the", "desk"],
      wrongIndex: 2,
      choices: ["are", "is", "be", "was"],
      answer: "are",
    },
    {
      level: "A1",
      sentence: "I likes to read comic books.",
      words: ["I", "likes", "to", "read", "comic", "books"],
      wrongIndex: 1,
      choices: ["like", "likes", "liking", "liked"],
      answer: "like",
    },
    {
      level: "A1",
      sentence: "Sarah have two small sisters.",
      words: ["Sarah", "have", "two", "small", "sisters"],
      wrongIndex: 1,
      choices: ["has", "have", "having", "had"],
      answer: "has",
    },
    {
      level: "A1",
      sentence: "The birds flies in the sky.",
      words: ["The", "birds", "flies", "in", "the", "sky"],
      wrongIndex: 2,
      choices: ["fly", "flies", "flying", "flew"],
      answer: "fly",
    },
    {
      level: "A1",
      sentence: "You is a great cook.",
      words: ["You", "is", "a", "great", "cook"],
      wrongIndex: 1,
      choices: ["are", "is", "am", "be"],
      answer: "are",
    },
    {
      level: "A1",
      sentence: "He do not speak French.",
      words: ["He", "do", "not", "speak", "French"],
      wrongIndex: 1,
      choices: ["does", "do", "doing", "did"],
      answer: "does",
    },
    {
      level: "A1",
      sentence: "My mother cook delicious food.",
      words: ["My", "mother", "cook", "delicious", "food"],
      wrongIndex: 2,
      choices: ["cooks", "cook", "cooking", "cooked"],
      answer: "cooks",
    },
    {
      level: "A1",
      sentence: "We has a brown dog.",
      words: ["We", "has", "a", "brown", "dog"],
      wrongIndex: 1,
      choices: ["have", "has", "having", "had"],
      answer: "have",
    },
    {
      level: "A1",
      sentence: "The children plays in the garden.",
      words: ["The", "children", "plays", "in", "the", "garden"],
      wrongIndex: 2,
      choices: ["play", "plays", "playing", "played"],
      answer: "play",
    },
    {
      level: "A1",
      sentence: "She are my best friend.",
      words: ["She", "are", "my", "best", "friend"],
      wrongIndex: 1,
      choices: ["is", "are", "am", "be"],
      answer: "is",
    },
    {
      level: "A1",
      sentence: "They reads books every night.",
      words: ["They", "reads", "books", "every", "night"],
      wrongIndex: 1,
      choices: ["read", "reads", "reading", "readed"],
      answer: "read",
    },
    {
      level: "A1",
      sentence: "He like to drink hot tea.",
      words: ["He", "like", "to", "drink", "hot", "tea"],
      wrongIndex: 1,
      choices: ["likes", "like", "liking", "liked"],
      answer: "likes",
    },
    {
      level: "A1",
      sentence: "I is a tall boy.",
      words: ["I", "is", "a", "tall", "boy"],
      wrongIndex: 1,
      choices: ["am", "is", "are", "be"],
      answer: "am",
    },
    {
      level: "A1",
      sentence: "The car go fast on roads.",
      words: ["The", "car", "go", "fast", "on", "roads"],
      wrongIndex: 2,
      choices: ["goes", "go", "going", "gone"],
      answer: "goes",
    },
    {
      level: "A1",
      sentence: "We studies English at school.",
      words: ["We", "studies", "English", "at", "school"],
      wrongIndex: 1,
      choices: ["study", "studies", "studying", "studied"],
      answer: "study",
    },
    {
      level: "A1",
      sentence: "My dad work very hard.",
      words: ["My", "dad", "work", "very", "hard"],
      wrongIndex: 2,
      choices: ["works", "work", "working", "worked"],
      answer: "works",
    },
    {
      level: "A1",
      sentence: "They has a big house.",
      words: ["They", "has", "a", "big", "house"],
      wrongIndex: 1,
      choices: ["have", "has", "having", "had"],
      answer: "have",
    },
    {
      level: "A1",
      sentence: "She watch TV every evening.",
      words: ["She", "watch", "TV", "every", "evening"],
      wrongIndex: 1,
      choices: ["watches", "watch", "watching", "watched"],
      answer: "watches",
    },
    {
      level: "A1",
      sentence: "The cat drink milk daily.",
      words: ["The", "cat", "drink", "milk", "daily"],
      wrongIndex: 2,
      choices: ["drinks", "drink", "drinking", "drank"],
      answer: "drinks",
    },
    {
      level: "A1",
      sentence: "It are a hot day.",
      words: ["It", "are", "a", "hot", "day"],
      wrongIndex: 1,
      choices: ["is", "are", "am", "be"],
      answer: "is",
    },
    {
      level: "A1",
      sentence: "My sister like the color red.",
      words: ["My", "sister", "like", "the", "color", "red"],
      wrongIndex: 2,
      choices: ["likes", "like", "liking", "liked"],
      answer: "likes",
    },
    {
      level: "A1",
      sentence: "They does work on Fridays.",
      words: ["They", "does", "work", "on", "Fridays"],
      wrongIndex: 1,
      choices: ["do", "does", "doing", "done"],
      answer: "do",
    },
    {
      level: "A1",
      sentence: "We is waiting for the bus.",
      words: ["We", "is", "waiting", "for", "the", "bus"],
      wrongIndex: 1,
      choices: ["are", "is", "am", "be"],
      answer: "are",
    },
    {
      level: "A1",
      sentence: "He have a green apple.",
      words: ["He", "have", "a", "green", "apple"],
      wrongIndex: 1,
      choices: ["has", "have", "having", "had"],
      answer: "has",
    },
    {
      level: "A1",
      sentence: "The students studies for the test.",
      words: ["The", "students", "studies", "for", "the", "test"],
      wrongIndex: 2,
      choices: ["study", "studies", "studying", "studied"],
      answer: "study",
    },
    {
      level: "A1",
      sentence: "She play guitar very well.",
      words: ["She", "play", "guitar", "very", "well"],
      wrongIndex: 1,
      choices: ["plays", "play", "playing", "played"],
      answer: "plays",
    },
    {
      level: "A1",
      sentence: "They is my family members.",
      words: ["They", "is", "my", "family", "members"],
      wrongIndex: 1,
      choices: ["are", "is", "am", "be"],
      answer: "are",
    },
    {
      level: "A1",
      sentence: "My dog like to run.",
      words: ["My", "dog", "like", "to", "run"],
      wrongIndex: 2,
      choices: ["likes", "like", "liking", "liked"],
      answer: "likes",
    },
    {
      level: "A1",
      sentence: "I does not eat fish.",
      words: ["I", "does", "not", "eat", "fish"],
      wrongIndex: 1,
      choices: ["do", "does", "doing", "done"],
      answer: "do",
    },
    {
      level: "A1",
      sentence: "He walk to school alone.",
      words: ["He", "walk", "to", "school", "alone"],
      wrongIndex: 1,
      choices: ["walks", "walk", "walking", "walked"],
      answer: "walks",
    },
    {
      level: "A1",
      sentence: "She have two brothers.",
      words: ["She", "have", "two", "brothers"],
      wrongIndex: 1,
      choices: ["has", "have", "having", "had"],
      answer: "has",
    },
    {
      level: "A1",
      sentence: "The boy like soccer.",
      words: ["The", "boy", "like", "soccer"],
      wrongIndex: 2,
      choices: ["likes", "like", "liking", "liked"],
      answer: "likes",
    },
    {
      level: "A1",
      sentence: "We does our work now.",
      words: ["We", "does", "our", "work", "now"],
      wrongIndex: 1,
      choices: ["do", "does", "doing", "done"],
      answer: "do",
    },
    {
      level: "A1",
      sentence: "They is happy today.",
      words: ["They", "is", "happy", "today"],
      wrongIndex: 1,
      choices: ["are", "is", "am", "be"],
      answer: "are",
    },
    {
      level: "A1",
      sentence: "My friend speak English.",
      words: ["My", "friend", "speak", "English"],
      wrongIndex: 2,
      choices: ["speaks", "speak", "speaking", "spoke"],
      answer: "speaks",
    },
    {
      level: "A1",
      sentence: "I has a small bag.",
      words: ["I", "has", "a", "small", "bag"],
      wrongIndex: 1,
      choices: ["have", "has", "having", "had"],
      answer: "have",
    },
    {
      level: "A1",
      sentence: "He play football on Sundays.",
      words: ["He", "play", "football", "on", "Sundays"],
      wrongIndex: 1,
      choices: ["plays", "play", "playing", "played"],
      answer: "plays",
    },
    {
      level: "A1",
      sentence: "The cat sleep in the box.",
      words: ["The", "cat", "sleep", "in", "the", "box"],
      wrongIndex: 2,
      choices: ["sleeps", "sleep", "sleeping", "slept"],
      answer: "sleeps",
    },
    {
      level: "A1",
      sentence: "She do her chores daily.",
      words: ["She", "do", "her", "chores", "daily"],
      wrongIndex: 1,
      choices: ["does", "do", "doing", "done"],
      answer: "does",
    },
    {
      level: "A1",
      sentence: "They is at the beach.",
      words: ["They", "is", "at", "the", "beach"],
      wrongIndex: 1,
      choices: ["are", "is", "am", "be"],
      answer: "are",
    },
    {
      level: "A1",
      sentence: "My mother like to cook.",
      words: ["My", "mother", "like", "to", "cook"],
      wrongIndex: 2,
      choices: ["likes", "like", "liking", "liked"],
      answer: "likes",
    },
    {
      level: "A1",
      sentence: "We has a blue car.",
      words: ["We", "has", "a", "blue", "car"],
      wrongIndex: 1,
      choices: ["have", "has", "having", "had"],
      answer: "have",
    },
    {
      level: "A1",
      sentence: "He eat an egg daily.",
      words: ["He", "eat", "an", "egg", "daily"],
      wrongIndex: 1,
      choices: ["eats", "eat", "eating", "eaten"],
      answer: "eats",
    },
    {
      level: "A1",
      sentence: "The dog bark at people.",
      words: ["The", "dog", "bark", "at", "people"],
      wrongIndex: 2,
      choices: ["barks", "bark", "barking", "barked"],
      answer: "barks",
    },
    {
      level: "A1",
      sentence: "She like to sing songs.",
      words: ["She", "like", "to", "sing", "songs"],
      wrongIndex: 1,
      choices: ["likes", "like", "liking", "liked"],
      answer: "likes",
    },
    {
      level: "A1",
      sentence: "They does their homework fast.",
      words: ["They", "does", "their", "homework", "fast"],
      wrongIndex: 1,
      choices: ["do", "does", "doing", "done"],
      answer: "do",
    },
    {
      level: "A1",
      sentence: "My brother are tall.",
      words: ["My", "brother", "are", "tall"],
      wrongIndex: 2,
      choices: ["is", "are", "am", "be"],
      answer: "is",
    },
    {
      level: "A1",
      sentence: "He has a new job.",
      words: ["He", "has", "a", "new", "job"],
      wrongIndex: 1,
      choices: ["has", "have", "having", "had"],
      answer: "has",
    },
    {
      level: "A1",
      sentence: "The rain fall in winter.",
      words: ["The", "rain", "fall", "in", "winter"],
      wrongIndex: 2,
      choices: ["falls", "fall", "falling", "fell"],
      answer: "falls",
    },
    {
      level: "A1",
      sentence: "She is a kind teacher.",
      words: ["She", "is", "a", "kind", "teacher"],
      wrongIndex: 1,
      choices: ["is", "are", "am", "be"],
      answer: "is",
    },
    {
      level: "A1",
      sentence: "They like to eat cake.",
      words: ["They", "like", "to", "eat", "cake"],
      wrongIndex: 1,
      choices: ["like", "likes", "liking", "liked"],
      answer: "like",
    },
    {
      level: "A1",
      sentence: "We do our exercises now.",
      words: ["We", "do", "our", "exercises", "now"],
      wrongIndex: 1,
      choices: ["do", "does", "doing", "done"],
      answer: "do",
    },
    {
      level: "A1",
      sentence: "My cat are white.",
      words: ["My", "cat", "are", "white"],
      wrongIndex: 2,
      choices: ["is", "are", "am", "be"],
      answer: "is",
    },
    {
      level: "A1",
      sentence: "I have a fast bike.",
      words: ["I", "have", "a", "fast", "bike"],
      wrongIndex: 1,
      choices: ["have", "has", "having", "had"],
      answer: "have",
    },
    {
      level: "A1",
      sentence: "He work in the city.",
      words: ["He", "work", "in", "the", "city"],
      wrongIndex: 1,
      choices: ["works", "work", "working", "worked"],
      answer: "works",
    },
    {
      level: "A1",
      sentence: "She has a nice dress.",
      words: ["She", "has", "a", "nice", "dress"],
      wrongIndex: 1,
      choices: ["has", "have", "having", "had"],
      answer: "has",
    },
    {
      level: "A1",
      sentence: "They plays games at home.",
      words: ["They", "plays", "games", "at", "home"],
      wrongIndex: 1,
      choices: ["play", "plays", "playing", "played"],
      answer: "play",
    },
    {
      level: "A1",
      sentence: "We is ready for school.",
      words: ["We", "is", "ready", "for", "school"],
      wrongIndex: 1,
      choices: ["are", "is", "am", "be"],
      answer: "are",
    },
    {
      level: "A1",
      sentence: "My sister likes to dance.",
      words: ["My", "sister", "likes", "to", "dance"],
      wrongIndex: 2,
      choices: ["likes", "like", "liking", "liked"],
      answer: "likes",
    },
    {
      level: "A1",
      sentence: "I do my job well.",
      words: ["I", "do", "my", "job", "well"],
      wrongIndex: 1,
      choices: ["do", "does", "doing", "done"],
      answer: "do",
    },
    {
      level: "A1",
      sentence: "The dog have a bone.",
      words: ["The", "dog", "have", "a", "bone"],
      wrongIndex: 2,
      choices: ["has", "have", "having", "had"],
      answer: "has",
    },
    {
      level: "A1",
      sentence: "She likes to drink juice.",
      words: ["She", "likes", "to", "drink", "juice"],
      wrongIndex: 1,
      choices: ["likes", "like", "liking", "liked"],
      answer: "likes",
    },
    {
      level: "A1",
      sentence: "They do their work carefully.",
      words: ["They", "do", "their", "work", "carefully"],
      wrongIndex: 1,
      choices: ["do", "does", "doing", "done"],
      answer: "do",
    },
    {
      level: "A1",
      sentence: "We is going to store.",
      words: ["We", "is", "going", "to", "store"],
      wrongIndex: 1,
      choices: ["are", "is", "am", "be"],
      answer: "are",
    },
    {
      level: "A1",
      sentence: "My dog like to bark.",
      words: ["My", "dog", "like", "to", "bark"],
      wrongIndex: 2,
      choices: ["likes", "like", "liking", "liked"],
      answer: "likes",
    },
    {
      level: "A1",
      sentence: "I have a red pen.",
      words: ["I", "have", "a", "red", "pen"],
      wrongIndex: 1,
      choices: ["have", "has", "having", "had"],
      answer: "have",
    },
    {
      level: "A1",
      sentence: "He walk in the park.",
      words: ["He", "walk", "in", "the", "park"],
      wrongIndex: 1,
      choices: ["walks", "walk", "walking", "walked"],
      answer: "walks",
    },
    {
      level: "A1",
      sentence: "The birds fly in pairs.",
      words: ["The", "birds", "fly", "in", "pairs"],
      wrongIndex: 2,
      choices: ["fly", "flies", "flying", "flew"],
      answer: "fly",
    },
    {
      level: "A1",
      sentence: "She has a small house.",
      words: ["She", "has", "a", "small", "house"],
      wrongIndex: 1,
      choices: ["has", "have", "having", "had"],
      answer: "has",
    },
    {
      level: "A1",
      sentence: "They like to swim daily.",
      words: ["They", "like", "to", "swim", "daily"],
      wrongIndex: 1,
      choices: ["like", "likes", "liking", "liked"],
      answer: "like",
    },
    {
      level: "A1",
      sentence: "We do our task today.",
      words: ["We", "do", "our", "task", "today"],
      wrongIndex: 1,
      choices: ["do", "does", "doing", "done"],
      answer: "do",
    },
    {
      level: "A1",
      sentence: "My cat likes to play.",
      words: ["My", "cat", "likes", "to", "play"],
      wrongIndex: 2,
      choices: ["likes", "like", "liking", "liked"],
      answer: "likes",
    },
    {
      level: "A1",
      sentence: "I am a young student.",
      words: ["I", "am", "a", "young", "student"],
      wrongIndex: 1,
      choices: ["am", "is", "are", "be"],
      answer: "am",
    },
    {
      level: "A1",
      sentence: "He has a busy day.",
      words: ["He", "has", "a", "busy", "day"],
      wrongIndex: 1,
      choices: ["has", "have", "having", "had"],
      answer: "has",
    },
    {
      level: "A1",
      sentence: "The stars shine at night.",
      words: ["The", "stars", "shine", "at", "night"],
      wrongIndex: 2,
      choices: ["shine", "shines", "shining", "shone"],
      answer: "shine",
    },
    {
      level: "A1",
      sentence: "She likes to eat fruit.",
      words: ["She", "likes", "to", "eat", "fruit"],
      wrongIndex: 1,
      choices: ["likes", "like", "liking", "liked"],
      answer: "likes",
    },
    {
      level: "A1",
      sentence: "They do work very well.",
      words: ["They", "do", "work", "very", "well"],
      wrongIndex: 1,
      choices: ["do", "does", "doing", "done"],
      answer: "do",
    },
    {
      level: "A1",
      sentence: "We are at the station.",
      words: ["We", "are", "at", "the", "station"],
      wrongIndex: 1,
      choices: ["are", "is", "am", "be"],
      answer: "are",
    },
    {
      level: "A1",
      sentence: "My brother like to run.",
      words: ["My", "brother", "like", "to", "run"],
      wrongIndex: 2,
      choices: ["likes", "like", "liking", "liked"],
      answer: "likes",
    },
    {
      level: "A1",
      sentence: "I have a big family.",
      words: ["I", "have", "a", "big", "family"],
      wrongIndex: 1,
      choices: ["have", "has", "having", "had"],
      answer: "have",
    },
    {
      level: "A1",
      sentence: "He works in a store.",
      words: ["He", "works", "in", "a", "store"],
      wrongIndex: 1,
      choices: ["works", "work", "working", "worked"],
      answer: "works",
    },
    {
      level: "A1",
      sentence: "The fish swim in water.",
      words: ["The", "fish", "swim", "in", "water"],
      wrongIndex: 2,
      choices: ["swim", "swims", "swimming", "swam"],
      answer: "swim",
    },
    {
      level: "A1",
      sentence: "She has a nice bike.",
      words: ["She", "has", "a", "nice", "bike"],
      wrongIndex: 1,
      choices: ["has", "have", "having", "had"],
      answer: "has",
    },
    {
      level: "A1",
      sentence: "They like to read books.",
      words: ["They", "like", "to", "read", "books"],
      wrongIndex: 1,
      choices: ["like", "likes", "liking", "liked"],
      answer: "like",
    },
    {
      level: "A1",
      sentence: "We do our homework together.",
      words: ["We", "do", "our", "homework", "together"],
      wrongIndex: 1,
      choices: ["do", "does", "doing", "done"],
      answer: "do",
    },
    {
      level: "A1",
      sentence: "I is a fast runner.",
      words: ["I", "is", "a", "fast", "runner"],
      wrongIndex: 1,
      choices: ["am", "is", "are", "be"],
      answer: "am",
    },
    {
      level: "A1",
      sentence: "They has four blue pens.",
      words: ["They", "has", "four", "blue", "pens"],
      wrongIndex: 1,
      choices: ["have", "has", "had", "having"],
      answer: "have",
    },
    {
      level: "A1",
      sentence: "She likes to swim here.",
      words: ["She", "likes", "to", "swim", "here"],
      wrongIndex: 1,
      choices: ["likes", "like", "liked", "liking"],
      answer: "likes",
    },
    {
      level: "A1",
      sentence: "He do his job well.",
      words: ["He", "do", "his", "job", "well"],
      wrongIndex: 1,
      choices: ["does", "do", "did", "doing"],
      answer: "does",
    },
    {
      level: "A1",
      sentence: "We is hungry right now.",
      words: ["We", "is", "hungry", "right", "now"],
      wrongIndex: 1,
      choices: ["are", "is", "am", "be"],
      answer: "are",
    },
    {
      level: "A1",
      sentence: "The dog bark at night.",
      words: ["The", "dog", "bark", "at", "night"],
      wrongIndex: 2,
      choices: ["barks", "bark", "barked", "barking"],
      answer: "barks",
    },
    {
      level: "A1",
      sentence: "You is the best cook.",
      words: ["You", "is", "the", "best", "cook"],
      wrongIndex: 1,
      choices: ["are", "is", "am", "be"],
      answer: "are",
    },
    {
      level: "A1",
      sentence: "I has a small room.",
      words: ["I", "has", "a", "small", "room"],
      wrongIndex: 1,
      choices: ["have", "has", "had", "having"],
      answer: "have",
    },
    {
      level: "A1",
      sentence: "She drink coffee every morning.",
      words: ["She", "drink", "coffee", "every", "morning"],
      wrongIndex: 1,
      choices: ["drinks", "drink", "drank", "drinking"],
      answer: "drinks",
    },
    {
      level: "A1",
      sentence: "They does help the poor.",
      words: ["They", "does", "help", "the", "poor"],
      wrongIndex: 1,
      choices: ["do", "does", "did", "doing"],
      answer: "do",
    },
    {
      level: "A1",
      sentence: "He am very strong today.",
      words: ["He", "am", "very", "strong", "today"],
      wrongIndex: 1,
      choices: ["is", "am", "are", "be"],
      answer: "is",
    },
    {
      level: "A1",
      sentence: "We has many good friends.",
      words: ["We", "has", "many", "good", "friends"],
      wrongIndex: 1,
      choices: ["have", "has", "had", "having"],
      answer: "have",
    },
    {
      level: "A1",
      sentence: "She loves to read news.",
      words: ["She", "loves", "to", "read", "news"],
      wrongIndex: 1,
      choices: ["loves", "love", "loved", "loving"],
      answer: "loves",
    },
    {
      level: "A1",
      sentence: "The boy run to school.",
      words: ["The", "boy", "run", "to", "school"],
      wrongIndex: 2,
      choices: ["runs", "run", "ran", "running"],
      answer: "runs",
    },
    {
      level: "A1",
      sentence: "They is smart and kind.",
      words: ["They", "is", "smart", "and", "kind"],
      wrongIndex: 1,
      choices: ["are", "is", "am", "be"],
      answer: "are",
    },
    {
      level: "A1",
      sentence: "I is in the kitchen.",
      words: ["I", "is", "in ", "the", "kitchen"],
      wrongIndex: 1,
      choices: ["am", "is", "are", "be"],
      answer: "am",
    },
    {
      level: "A1",
      sentence: "He have a big computer.",
      words: ["He", "have", "a", "big", "computer"],
      wrongIndex: 1,
      choices: ["has", "have", "had", "having"],
      answer: "has",
    },
    {
      level: "A1",
      sentence: "She do exercise at gym.",
      words: ["She", "do", "exercise", "at", "gym"],
      wrongIndex: 1,
      choices: ["does", "do", "did", "doing"],
      answer: "does",
    },
    {
      level: "A1",
      sentence: "We is ready for class.",
      words: ["We", "is", "ready", "for", "class"],
      wrongIndex: 1,
      choices: ["are", "is", "am", "be"],
      answer: "are",
    },
    {
      level: "A1",
      sentence: "The birds fly in sky.",
      words: ["The", "birds", "fly", "in ", "sky"],
      wrongIndex: 2,
      choices: ["fly", "flies", "flew", "flying"],
      answer: "fly",
    },
    {
      level: "A2",
      sentence: "She used to living there.",
      words: ["She", "used", "to", "living", "there"],
      wrongIndex: 3,
      choices: ["live", "living", "lived", "lives"],
      answer: "live",
    },
    {
      level: "A2",
      sentence: "They was playing soccer yesterday.",
      words: ["They", "was", "playing", "soccer", "yesterday"],
      wrongIndex: 1,
      choices: ["were", "was", "are", "been"],
      answer: "were",
    },
    {
      level: "A2",
      sentence: "I have already eat breakfast.",
      words: ["I", "have", "already", "eat", "breakfast"],
      wrongIndex: 3,
      choices: ["eat", "eaten", "ate", "eating"],
      answer: "eaten",
    },
    {
      level: "A2",
      sentence: "He is more taller than me.",
      words: ["He", "is", "more", "taller", "than", "me"],
      wrongIndex: 2,
      choices: ["much", "very", "more", "none"],
      answer: "none",
    },
    {
      level: "A2",
      sentence: "She did not went home.",
      words: ["She", "did", "not", "went", "home"],
      wrongIndex: 3,
      choices: ["go", "went", "gone", "goes"],
      answer: "go",
    },
    {
      level: "A2",
      sentence: "We was walking in park.",
      words: ["We", "was", "walking", "in", "park"],
      wrongIndex: 1,
      choices: ["were", "was", "are", "been"],
      answer: "were",
    },
    {
      level: "A2",
      sentence: "They have went to London.",
      words: ["They", "have", "went", "to", "London"],
      wrongIndex: 2,
      choices: ["gone", "went", "go", "going"],
      answer: "gone",
    },
    {
      level: "A2",
      sentence: "It is the more big house.",
      words: ["It", "is", "the", "more", "big", "house"],
      wrongIndex: 3,
      choices: ["most", "more", "much", "very"],
      answer: "most",
    },
    {
      level: "A2",
      sentence: "She can swimming very well.",
      words: ["She", "can", "swimming", "very", "well"],
      wrongIndex: 2,
      choices: ["swim", "swimming", "swam", "swims"],
      answer: "swim",
    },
    {
      level: "A2",
      sentence: "They has been friends long.",
      words: ["They", "has", "been", "friends", "long"],
      wrongIndex: 1,
      choices: ["have", "has", "had", "having"],
      answer: "have",
    },
    {
      level: "A2",
      sentence: "I was study when he arrived.",
      words: ["I", "was", "study", "when", "he", "arrived"],
      wrongIndex: 2,
      choices: ["studying", "study", "studied", "studies"],
      answer: "studying",
    },
    {
      level: "A2",
      sentence: "She go to work yesterday.",
      words: ["She", "go", "to", "work", "yesterday"],
      wrongIndex: 1,
      choices: ["went", "go", "goes", "gone"],
      answer: "went",
    },
    {
      level: "A2",
      sentence: "We has seen this movie.",
      words: ["We", "has", "seen", "this", "movie"],
      wrongIndex: 1,
      choices: ["have", "has", "had", "having"],
      answer: "have",
    },
    {
      level: "A2",
      sentence: "He is best than his brother.",
      words: ["He", "is", "best", "than", "his", "brother"],
      wrongIndex: 2,
      choices: ["better", "best", "good", "well"],
      answer: "better",
    },
    {
      level: "A2",
      sentence: "Did you finished your homework?",
      words: ["Did", "you", "finished", "your", "homework"],
      wrongIndex: 2,
      choices: ["finish", "finished", "finishing", "finishes"],
      answer: "finish",
    },
    {
      level: "A2",
      sentence: "They were drive to school.",
      words: ["They", "were", "drive", "to", "school"],
      wrongIndex: 2,
      choices: ["driving", "drive", "drove", "driven"],
      answer: "driving",
    },
    {
      level: "A2",
      sentence: "She has study for hours.",
      words: ["She", "has", "study", "for", "hours"],
      wrongIndex: 2,
      choices: ["studied", "study", "studying", "studies"],
      answer: "studied",
    },
    {
      level: "A2",
      sentence: "She was watch TV alone.",
      words: ["She", "was", "watch", "TV", "alone"],
      wrongIndex: 2,
      choices: ["watching", "watch", "watched", "watches"],
      answer: "watching",
    },
    {
      level: "A2",
      sentence: "They did not saw me.",
      words: ["They", "did", "not", "saw", "me"],
      wrongIndex: 3,
      choices: ["see", "saw", "seen", "seeing"],
      answer: "see",
    },
    {
      level: "A2",
      sentence: "He have buyed some milk.",
      words: ["He", "have", "buyed", "some", "milk"],
      wrongIndex: 1,
      choices: ["has", "have", "had", "having"],
      answer: "has",
    },
    {
      level: "A2",
      sentence: "The cake is most good.",
      words: ["The", "cake", "is", "most", "good"],
      wrongIndex: 3,
      choices: ["better", "best", "more", "very"],
      answer: "best",
    },
    {
      level: "A2",
      sentence: "We are going to buyed food.",
      words: ["We", "are", "going", "to", "buyed", "food"],
      wrongIndex: 4,
      choices: ["buy", "bought", "buying", "buys"],
      answer: "buy",
    },
    {
      level: "A2",
      sentence: "She were at the beach.",
      words: ["She", "were", "at", "the", "beach"],
      wrongIndex: 1,
      choices: ["was", "were", "is", "are"],
      answer: "was",
    },
    {
      level: "A2",
      sentence: "They have visit the city.",
      words: ["They", "have", "visit", "the", "city"],
      wrongIndex: 2,
      choices: ["visited", "visit", "visiting", "visits"],
      answer: "visited",
    },
    {
      level: "A2",
      sentence: "He was run to the bus.",
      words: ["He", "was", "run", "to", "the", "bus"],
      wrongIndex: 2,
      choices: ["running", "run", "ran", "runs"],
      answer: "running",
    },
    {
      level: "A2",
      sentence: "I am more tall than you.",
      words: ["I", "am", "more", "tall", "than", "you"],
      wrongIndex: 2,
      choices: ["taller", "more", "very", "most"],
      answer: "taller",
    },
    {
      level: "A2",
      sentence: "Did she cook dinner yesterday?",
      words: ["Did", "she", "cook", "dinner", "yesterday"],
      wrongIndex: 2,
      choices: ["cooked", "cook", "cooking", "cooks"],
      answer: "cook",
    },
    {
      level: "A2",
      sentence: "We has been here before.",
      words: ["We", "has", "been", "here", "before"],
      wrongIndex: 1,
      choices: ["have", "has", "had", "having"],
      answer: "have",
    },
    {
      level: "A2",
      sentence: "She used to played golf.",
      words: ["She", "used", "to", "played", "golf"],
      wrongIndex: 3,
      choices: ["play", "played", "playing", "plays"],
      answer: "play",
    },
    {
      level: "A2",
      sentence: "They are more busy today.",
      words: ["They", "are", "more", "busy", "today"],
      wrongIndex: 2,
      choices: ["busier", "more", "most", "very"],
      answer: "busier",
    },
    {
      level: "A2",
      sentence: "I has finish my work.",
      words: ["I", "has", "finish", "my", "work"],
      wrongIndex: 1,
      choices: ["have", "has", "had", "having"],
      answer: "have",
    },
    {
      level: "A2",
      sentence: "He were eating his lunch.",
      words: ["He", "were", "eating", "his", "lunch"],
      wrongIndex: 1,
      choices: ["was", "were", "is", "are"],
      answer: "was",
    },
    {
      level: "A2",
      sentence: "They did not played well.",
      words: ["They", "did", "not", "played", "well"],
      wrongIndex: 3,
      choices: ["play", "played", "playing", "plays"],
      answer: "play",
    },
    {
      level: "A2",
      sentence: "She has write a letter.",
      words: ["She", "has", "write", "a", "letter"],
      wrongIndex: 2,
      choices: ["written", "wrote", "write", "writing"],
      answer: "written",
    },
    {
      level: "A2",
      sentence: "It is the most big dog.",
      words: ["It", "is", "the", "most", "big", "dog"],
      wrongIndex: 3,
      choices: ["biggest", "most", "more", "very"],
      answer: "biggest",
    },
    {
      level: "A2",
      sentence: "We was sing in choir.",
      words: ["We", "was", "sing", "in", "choir"],
      wrongIndex: 1,
      choices: ["were", "was", "are", "is"],
      answer: "were",
    },
    {
      level: "A2",
      sentence: "He have gone to school.",
      words: ["He", "have", "gone", "to", "school"],
      wrongIndex: 1,
      choices: ["has", "have", "had", "having"],
      answer: "has",
    },
    {
      level: "A2",
      sentence: "She is more fast than him.",
      words: ["She", "is", "more", "fast", "than", "him"],
      wrongIndex: 2,
      choices: ["faster", "more", "very", "most"],
      answer: "faster",
    },
    {
      level: "A2",
      sentence: "They have drank the water.",
      words: ["They", "have", "drank", "the", "water"],
      wrongIndex: 2,
      choices: ["drunk", "drank", "drink", "drinking"],
      answer: "drunk",
    },
    {
      level: "A2",
      sentence: "I were at home yesterday.",
      words: ["I", "were", "at", "home", "yesterday"],
      wrongIndex: 1,
      choices: ["was", "were", "is", "are"],
      answer: "was",
    },
    {
      level: "A2",
      sentence: "Did they goes to park?",
      words: ["Did", "they", "goes", "to", "park"],
      wrongIndex: 2,
      choices: ["go", "goes", "went", "going"],
      answer: "go",
    },
    {
      level: "A2",
      sentence: "She has been see him.",
      words: ["She", "has", "been", "see", "him"],
      wrongIndex: 3,
      choices: ["seeing", "see", "seen", "saw"],
      answer: "seeing",
    },
    {
      level: "A2",
      sentence: "We are more strong now.",
      words: ["We", "are", "more", "strong", "now"],
      wrongIndex: 2,
      choices: ["stronger", "more", "very", "most"],
      answer: "stronger",
    },
    {
      level: "A2",
      sentence: "He was sleeping at class.",
      words: ["He", "was", "sleeping", "at", "class"],
      wrongIndex: 2,
      choices: ["in", "at", "on", "to"],
      answer: "in",
    },
    {
      level: "A2",
      sentence: "They has done the job.",
      words: ["They", "has", "done", "the", "job"],
      wrongIndex: 1,
      choices: ["have", "has", "had", "having"],
      answer: "have",
    },
    {
      level: "A2",
      sentence: "I used to eats fish.",
      words: ["I", "used", "to", "eats", "fish"],
      wrongIndex: 3,
      choices: ["eat", "eats", "ate", "eating"],
      answer: "eat",
    },
    {
      level: "A2",
      sentence: "She was buy a car.",
      words: ["She", "was", "buy", "a", "car"],
      wrongIndex: 2,
      choices: ["buying", "buy", "bought", "buys"],
      answer: "buying",
    },
    {
      level: "A2",
      sentence: "It is the more funny movie.",
      words: ["It", "is", "the", "more", "funny", "movie"],
      wrongIndex: 3,
      choices: ["funniest", "more", "most", "very"],
      answer: "funniest",
    },
    {
      level: "A2",
      sentence: "We did not spoke English.",
      words: ["We", "did", "not", "spoke", "English"],
      wrongIndex: 3,
      choices: ["speak", "spoke", "spoken", "speaking"],
      answer: "speak",
    },
    {
      level: "A2",
      sentence: "He have already finish lunch.",
      words: ["He", "have", "already", "finish", "lunch"],
      wrongIndex: 1,
      choices: ["has", "have", "had", "having"],
      answer: "has",
    },
    {
      level: "A2",
      sentence: "They were wait for bus.",
      words: ["They", "were", "wait", "for", "bus"],
      wrongIndex: 2,
      choices: ["waiting", "wait", "waited", "waits"],
      answer: "waiting",
    },
    {
      level: "A2",
      sentence: "She is more thin now.",
      words: ["She", "is", "more", "thin", "now"],
      wrongIndex: 2,
      choices: ["thinner", "more", "most", "very"],
      answer: "thinner",
    },
    {
      level: "A2",
      sentence: "I have broke the glass.",
      words: ["I", "have", "broke", "the", "glass"],
      wrongIndex: 2,
      choices: ["broken", "broke", "break", "breaking"],
      answer: "broken",
    },
    {
      level: "A2",
      sentence: "Did you heard that sound?",
      words: ["Did", "you", "heard", "that", "sound"],
      wrongIndex: 2,
      choices: ["hear", "heard", "hearing", "hears"],
      answer: "hear",
    },
    {
      level: "A2",
      sentence: "They was reading a book.",
      words: ["They", "was", "reading", "a", "book"],
      wrongIndex: 1,
      choices: ["were", "was", "is", "are"],
      answer: "were",
    },
    {
      level: "A2",
      sentence: "She has build a house.",
      words: ["She", "has", "build", "a", "house"],
      wrongIndex: 2,
      choices: ["built", "build", "building", "builds"],
      answer: "built",
    },
    {
      level: "A2",
      sentence: "He is most fast runner.",
      words: ["He", "is", "most", "fast", "runner"],
      wrongIndex: 2,
      choices: ["the", "most", "more", "very"],
      answer: "the",
    },
    {
      level: "A2",
      sentence: "We used to living here.",
      words: ["We", "used", "to", "living", "here"],
      wrongIndex: 3,
      choices: ["live", "living", "lived", "lives"],
      answer: "live",
    },
    {
      level: "A2",
      sentence: "They are have a party.",
      words: ["They", "are", "have", "a", "party"],
      wrongIndex: 2,
      choices: ["having", "have", "had", "has"],
      answer: "having",
    },
    {
      level: "A2",
      sentence: "I was drive to work.",
      words: ["I", "was", "drive", "to", "work"],
      wrongIndex: 2,
      choices: ["driving", "drive", "drove", "driven"],
      answer: "driving",
    },
    {
      level: "A2",
      sentence: "She have lose her keys.",
      words: ["She", "have", "lose", "her", "keys"],
      wrongIndex: 1,
      choices: ["has", "have", "had", "having"],
      answer: "has",
    },
    {
      level: "A2",
      sentence: "The test is more easy.",
      words: ["The", "test", "is", "more", "easy"],
      wrongIndex: 3,
      choices: ["easier", "more", "most", "very"],
      answer: "easier",
    },
    {
      level: "A2",
      sentence: "We did not seen him.",
      words: ["We", "did", "not", "seen", "him"],
      wrongIndex: 3,
      choices: ["see", "seen", "saw", "seeing"],
      answer: "see",
    },
    {
      level: "A2",
      sentence: "He has took the book.",
      words: ["He", "has", "took", "the", "book"],
      wrongIndex: 2,
      choices: ["taken", "took", "take", "taking"],
      answer: "taken",
    },
    {
      level: "A2",
      sentence: "They was playing with dogs.",
      words: ["They", "was", "playing", "with", "dogs"],
      wrongIndex: 1,
      choices: ["were", "was", "is", "are"],
      answer: "were",
    },
    {
      level: "A2",
      sentence: "I am more happy today.",
      words: ["I", "am", "more", "happy", "today"],
      wrongIndex: 2,
      choices: ["happier", "more", "most", "very"],
      answer: "happier",
    },
    {
      level: "A2",
      sentence: "She have read this book.",
      words: ["She", "have", "read", "this", "book"],
      wrongIndex: 1,
      choices: ["has", "have", "had", "having"],
      answer: "has",
    },
    {
      level: "A2",
      sentence: "We were walk to town.",
      words: ["We", "were", "walk", "to", "town"],
      wrongIndex: 2,
      choices: ["walking", "walk", "walked", "walks"],
      answer: "walking",
    },
    {
      level: "A2",
      sentence: "They are more big now.",
      words: ["They", "are", "more", "big", "now"],
      wrongIndex: 2,
      choices: ["bigger", "more", "most", "very"],
      answer: "bigger",
    },
    {
      level: "A2",
      sentence: "Did she find the keys?",
      words: ["Did", "she", "find", "the", "keys"],
      wrongIndex: 0,
      choices: ["did", "does", "do", "has"],
      answer: "did",
    },
    {
      level: "A2",
      sentence: "He has sleep for hours.",
      words: ["He", "has", "sleep", "for", "hours"],
      wrongIndex: 2,
      choices: ["slept", "sleep", "sleeping", "sleeps"],
      answer: "slept",
    },
    {
      level: "A2",
      sentence: "I were at the store.",
      words: ["I", "were", "at", "the", "store"],
      wrongIndex: 1,
      choices: ["was", "were", "is", "are"],
      answer: "was",
    },
    {
      level: "A2",
      sentence: "She used to play games.",
      words: ["She", "used", "to", "play", "games"],
      wrongIndex: 1,
      choices: ["used", "use", "using", "uses"],
      answer: "used",
    },
    {
      level: "A2",
      sentence: "They have do their work.",
      words: ["They", "have", "do", "their", "work"],
      wrongIndex: 2,
      choices: ["done", "do", "did", "doing"],
      answer: "done",
    },
    {
      level: "A2",
      sentence: "It is the most bad day.",
      words: ["It", "is", "the", "most", "bad", "day"],
      wrongIndex: 3,
      choices: ["worst", "most", "more", "very"],
      answer: "worst",
    },
    {
      level: "A2",
      sentence: "We were study for exam.",
      words: ["We", "were", "study", "for", "exam"],
      wrongIndex: 2,
      choices: ["studying", "study", "studied", "studies"],
      answer: "studying",
    },
    {
      level: "A2",
      sentence: "He have gone to sleep.",
      words: ["He", "have", "gone", "to", "sleep"],
      wrongIndex: 1,
      choices: ["has", "have", "had", "having"],
      answer: "has",
    },
    {
      level: "A2",
      sentence: "She is more tall today.",
      words: ["She", "is", "more", "tall", "today"],
      wrongIndex: 2,
      choices: ["taller", "more", "most", "very"],
      answer: "taller",
    },
    {
      level: "A2",
      sentence: "They did not eat food.",
      words: ["They", "did", "not", "eat", "food"],
      wrongIndex: 3,
      choices: ["eat", "eats", "ate", "eating"],
      answer: "eat",
    },
    {
      level: "A2",
      sentence: "I have see the film.",
      words: ["I", "have", "see", "the", "film"],
      wrongIndex: 2,
      choices: ["seen", "see", "saw", "seeing"],
      answer: "seen",
    },
    {
      level: "A2",
      sentence: "He was run to help.",
      words: ["He", "was", "run", "to", "help"],
      wrongIndex: 2,
      choices: ["running", "run", "ran", "runs"],
      answer: "running",
    },
    {
      level: "A2",
      sentence: "They have finish the game.",
      words: ["They", "have", "finish", "the", "game"],
      wrongIndex: 2,
      choices: ["finished", "finish", "finishing", "finishes"],
      answer: "finished",
    },
    {
      level: "A2",
      sentence: "She were at work late.",
      words: ["She", "were", "at", "work", "late"],
      wrongIndex: 1,
      choices: ["was", "were", "is", "are"],
      answer: "was",
    },
    {
      level: "A2",
      sentence: "We are more busy today.",
      words: ["We", "are", "more", "busy", "today"],
      wrongIndex: 2,
      choices: ["busier", "more", "most", "very"],
      answer: "busier",
    },
    {
      level: "A2",
      sentence: "Did they played the game?",
      words: ["Did", "they", "played", "the", "game"],
      wrongIndex: 2,
      choices: ["play", "played", "playing", "plays"],
      answer: "play",
    },
    {
      level: "A2",
      sentence: "He has eat the meal.",
      words: ["He", "has", "eat", "the", "meal"],
      wrongIndex: 2,
      choices: ["eaten", "eat", "ate", "eating"],
      answer: "eaten",
    },
    {
      level: "A2",
      sentence: "I were reading a book.",
      words: ["I", "were", "reading", "a", "book"],
      wrongIndex: 1,
      choices: ["was", "were", "am", "is"],
      answer: "was",
    },
    {
      level: "A2",
      sentence: "She is more fast runner.",
      words: ["She", "is", "more", "fast", "runner"],
      wrongIndex: 2,
      choices: ["a", "more", "the", "very"],
      answer: "a",
    },
    {
      level: "A2",
      sentence: "They have go to work.",
      words: ["They", "have", "go", "to", "work"],
      wrongIndex: 2,
      choices: ["gone", "go", "went", "going"],
      answer: "gone",
    },
    {
      level: "A2",
      sentence: "We did not sing songs.",
      words: ["We", "did", "not", "sing", "songs"],
      wrongIndex: 3,
      choices: ["sing", "sang", "sung", "singing"],
      answer: "sing",
    },
    {
      level: "A2",
      sentence: "He was write a story.",
      words: ["He", "was", "write", "a", "story"],
      wrongIndex: 2,
      choices: ["writing", "write", "wrote", "written"],
      answer: "writing",
    },
    {
      level: "A2",
      sentence: "She has been in Paris.",
      words: ["She", "has", "been", "in", "Paris"],
      wrongIndex: 1,
      choices: ["has", "have", "had", "having"],
      answer: "has",
    },
    {
      level: "A2",
      sentence: "They are most tall students.",
      words: ["They", "are", "most", "tall", "students"],
      wrongIndex: 2,
      choices: ["the", "most", "more", "very"],
      answer: "the",
    },
    {
      level: "A2",
      sentence: "I used to drink tea.",
      words: ["I", "used", "to", "drink", "tea"],
      wrongIndex: 1,
      choices: ["used", "use", "using", "uses"],
      answer: "used",
    },
    {
      level: "A2",
      sentence: "She have build a nest.",
      words: ["She", "have", "build", "a", "nest"],
      wrongIndex: 1,
      choices: ["has", "have", "had", "having"],
      answer: "has",
    },
    {
      level: "A2",
      sentence: "We were sleep all day.",
      words: ["We", "were", "sleep", "all", "day"],
      wrongIndex: 2,
      choices: ["sleeping", "sleep", "slept", "sleeps"],
      answer: "sleeping",
    },
    {
      level: "A2",
      sentence: "They are more happy now.",
      words: ["They", "are", "more", "happy", "now"],
      wrongIndex: 2,
      choices: ["happier", "more", "most", "very"],
      answer: "happier",
    },
    {
      level: "A2",
      sentence: "Did she see the bird?",
      words: ["Did", "she", "see", "the", "bird"],
      wrongIndex: 0,
      choices: ["did", "does", "do", "has"],
      answer: "did",
    },
    {
      level: "A2",
      sentence: "He has done the work.",
      words: ["He", "has", "done", "the", "work"],
      wrongIndex: 1,
      choices: ["has", "have", "had", "having"],
      answer: "has",
    },
  ];

  let count = 0;
  for (const item of GrammarData) {
    const exists = await prisma.grammarQuestion.findFirst({
      where: { level: item.level, sentence: item.sentence },
    });
    if (!exists) {
      await prisma.grammarQuestion.create({ data: item });
      count++;
    }
  }

  console.log(`✅ ${count} grammar questions seeded`);
  return count;
}

module.exports = { seedGrammar };
