async function seedListening(prisma) {
  const listeningSeeds = [
    {
      level: "A1",
      chunks: ["eat", "I", "apple", "an", "cat"],
      answer: ["I", "eat", "an", "apple"],
      sentences: "I eat an apple",
    },
    {
      level: "A1",
      chunks: ["is", "She", "my", "dog", "sister"],
      answer: ["She", "is", "my", "sister"],
      sentences: "She is my sister",
    },
    {
      level: "A1",
      chunks: ["book", "He", "reads", "a", "run"],
      answer: ["He", "reads", "a", "book"],
      sentences: "He reads a book",
    },
    {
      level: "A1",
      chunks: ["go", "We", "to", "school", "home"],
      answer: ["We", "go", "to", "school"],
      sentences: "We go to school",
    },
    {
      level: "A1",
      chunks: ["car", "has", "a", "They", "red"],
      answer: ["They", "have", "a", "car"],
      sentences: "They have a car",
    },
    {
      level: "A1",
      chunks: ["is", "hot", "Today", "it", "food"],
      answer: ["Today", "is", "hot"],
      sentences: "Today is hot",
    },
    {
      level: "A1",
      chunks: ["milk", "drink", "I", "like", "cat"],
      answer: ["I", "drink", "milk"],
      sentences: "I drink milk",
    },
    {
      level: "A1",
      chunks: ["happy", "is", "She", "very", "run"],
      answer: ["She", "is", "very", "happy"],
      sentences: "She is very happy",
    },
    {
      level: "A1",
      chunks: ["play", "They", "the", "ball", "cat"],
      answer: ["They", "play", "ball"],
      sentences: "They play ball",
    },
    {
      level: "A1",
      chunks: ["my", "is", "This", "pen", "dog"],
      answer: ["This", "is", "my", "pen"],
      sentences: "This is my pen",
    },
    {
      level: "A1",
      chunks: ["you", "Do", "eat", "pizza", "run"],
      answer: ["Do", "you", "eat", "pizza"],
      sentences: "Do you eat pizza",
    },
    {
      level: "A1",
      chunks: ["blue", "sky", "The", "is", "book"],
      answer: ["The", "sky", "is", "blue"],
      sentences: "The sky is blue",
    },
    {
      level: "A1",
      chunks: ["He", "a", "doctor", "is", "cat"],
      answer: ["He", "is", "a", "doctor"],
      sentences: "He is a doctor",
    },
    {
      level: "A1",
      chunks: ["my", "is", "Where", "bag", "run"],
      answer: ["Where", "is", "my", "bag"],
      sentences: "Where is my bag",
    },
    {
      level: "A1",
      chunks: ["good", "You", "very", "are", "food"],
      answer: ["You", "are", "very", "good"],
      sentences: "You are very good",
    },
    {
      level: "A1",
      chunks: ["cat", "The", "is", "small", "book"],
      answer: ["The", "cat", "is", "small"],
      sentences: "The cat is small",
    },
    {
      level: "A1",
      chunks: ["water", "I", "need", "some", "dog"],
      answer: ["I", "need", "some", "water"],
      sentences: "I need some water",
    },
    {
      level: "A1",
      chunks: ["my", "is", "Name", "is", "Tom", "dog"],
      answer: ["My", "name", "is", "Tom"],
      sentences: "My name is Tom",
    },
    {
      level: "A1",
      chunks: ["They", "are", "at", "home", "eat"],
      answer: ["They", "are", "at", "home"],
      sentences: "They are at home",
    },
    {
      level: "A1",
      chunks: ["has", "a", "big", "She", "pen", "dog"],
      answer: ["She", "has", "a", "big", "pen"],
      sentences: "She has a big pen",
    },
    {
      level: "A1",
      chunks: ["It", "is", "a", "cold", "day", "cat"],
      answer: ["It", "is", "a", "cold", "day"],
      sentences: "It is a cold day",
    },
    {
      level: "A1",
      chunks: ["We", "like", "the", "red", "car", "run"],
      answer: ["We", "like", "the", "red", "car"],
      sentences: "We like the red car",
    },
    {
      level: "A1",
      chunks: ["He", "can", "run", "very", "fast", "book"],
      answer: ["He", "can", "run", "very", "fast"],
      sentences: "He can run very fast",
    },
    {
      level: "A1",
      chunks: ["That", "is", "my", "new", "dog", "eat"],
      answer: ["That", "is", "my", "new", "dog"],
      sentences: "That is my new dog",
    },
    {
      level: "A1",
      chunks: ["Do", "you", "speak", "English", "now", "food"],
      answer: ["Do", "you", "speak", "English"],
      sentences: "Do you speak English",
    },
    {
      level: "A1",
      chunks: ["I", "have", "two", "blue", "pens", "cat"],
      answer: ["I", "have", "two", "blue", "pens"],
      sentences: "I have two blue pens",
    },
    {
      level: "A1",
      chunks: ["She", "is", "in", "the", "kitchen", "dog"],
      answer: ["She", "is", "in", "the", "kitchen"],
      sentences: "She is in the kitchen",
    },
    {
      level: "A1",
      chunks: ["The", "kids", "are", "very", "loud", "pen"],
      answer: ["The", "kids", "are", "very", "loud"],
      sentences: "The kids are very loud",
    },
    {
      level: "A1",
      chunks: ["I", "go", "to", "sleep", "early", "cat"],
      answer: ["I", "go", "to", "sleep", "early"],
      sentences: "I go to sleep early",
    },
    {
      level: "A1",
      chunks: ["He", "likes", "to", "play", "games", "food"],
      answer: ["He", "likes", "to", "play", "games"],
      sentences: "He likes to play games",
    },
    {
      level: "A1",
      chunks: ["We", "eat", "lunch", "at", "one", "run"],
      answer: ["We", "eat", "lunch", "at", "one"],
      sentences: "We eat lunch at one",
    },
    {
      level: "A1",
      chunks: ["My", "mom", "is", "a", "teacher", "dog"],
      answer: ["My", "mom", "is", "a", "teacher"],
      sentences: "My mom is a teacher",
    },
    {
      level: "A1",
      chunks: ["This", "tea", "is", "very", "hot", "book"],
      answer: ["This", "tea", "is", "very", "hot"],
      sentences: "This tea is very hot",
    },
    {
      level: "A1",
      chunks: ["They", "walk", "to", "the", "park", "cat"],
      answer: ["They", "walk", "to", "the", "park"],
      sentences: "They walk to the park",
    },
    {
      level: "A1",
      chunks: ["Is", "he", "your", "best", "friend", "eat"],
      answer: ["Is", "he", "your", "best", "friend"],
      sentences: "Is he your best friend",
    },
    {
      level: "A1",
      chunks: ["I", "am", "from", "New", "York", "dog"],
      answer: ["I", "am", "from", "New", "York"],
      sentences: "I am from New York",
    },
    {
      level: "A1",
      chunks: ["The", "book", "is", "on", "the", "desk", "run"],
      answer: ["The", "book", "is", "on", "the", "desk"],
      sentences: "The book is on the desk",
    },
    {
      level: "A1",
      chunks: ["She", "needs", "a", "new", "coat", "food"],
      answer: ["She", "needs", "a", "new", "coat"],
      sentences: "She needs a new coat",
    },
    {
      level: "A1",
      chunks: ["We", "have", "a", "big", "house", "cat"],
      answer: ["We", "have", "a", "big", "house"],
      sentences: "We have a big house",
    },
    {
      level: "A1",
      chunks: ["He", "wears", "a", "white", "shirt", "dog"],
      answer: ["He", "wears", "a", "white", "shirt"],
      sentences: "He wears a white shirt",
    },
    {
      level: "A1",
      chunks: ["Do", "they", "want", "some", "coffee", "run"],
      answer: ["Do", "they", "want", "some", "coffee"],
      sentences: "Do they want some coffee",
    },
    {
      level: "A1",
      chunks: ["It", "is", "time", "to", "go", "food"],
      answer: ["It", "is", "time", "to", "go"],
      sentences: "It is time to go",
    },
    {
      level: "A1",
      chunks: ["I", "see", "a", "small", "bird", "cat"],
      answer: ["I", "see", "a", "small", "bird"],
      sentences: "I see a small bird",
    },
    {
      level: "A1",
      chunks: ["She", "is", "my", "math", "teacher", "dog"],
      answer: ["She", "is", "my", "math", "teacher"],
      sentences: "She is my math teacher",
    },
    {
      level: "A1",
      chunks: ["They", "are", "watching", "a", "movie", "run"],
      answer: ["They", "are", "watching", "a", "movie"],
      sentences: "They are watching a movie",
    },
    {
      level: "A1",
      chunks: ["I", "can", "swim", "in", "the", "pool", "food"],
      answer: ["I", "can", "swim", "in", "the", "pool"],
      sentences: "I can swim in the pool",
    },
    {
      level: "A1",
      chunks: ["He", "is", "a", "good", "student", "cat"],
      answer: ["He", "is", "a", "good", "student"],
      sentences: "He is a good student",
    },
    {
      level: "A1",
      chunks: ["My", "dad", "has", "a", "black", "hat", "dog"],
      answer: ["My", "dad", "has", "a", "black", "hat"],
      sentences: "My dad has a black hat",
    },
    {
      level: "A1",
      chunks: ["Do", "you", "like", "this", "song", "run"],
      answer: ["Do", "you", "like", "this", "song"],
      sentences: "Do you like this song",
    },
    {
      level: "A1",
      chunks: ["The", "train", "is", "very", "fast", "food"],
      answer: ["The", "train", "is", "very", "fast"],
      sentences: "The train is very fast",
    },
    {
      level: "A1",
      chunks: ["I", "do", "not", "have", "money", "cat"],
      answer: ["I", "do", "not", "have", "money"],
      sentences: "I do not have money",
    },
    {
      level: "A1",
      chunks: ["She", "is", "a", "pretty", "girl", "dog"],
      answer: ["She", "is", "a", "pretty", "girl"],
      sentences: "She is a pretty girl",
    },
    {
      level: "A1",
      chunks: ["They", "are", "our", "new", "friends", "run"],
      answer: ["They", "are", "our", "new", "friends"],
      sentences: "They are our new friends",
    },
    {
      level: "A1",
      chunks: ["He", "bought", "a", "new", "computer", "food"],
      answer: ["He", "bought", "a", "new", "computer"],
      sentences: "He bought a new computer",
    },
    {
      level: "A1",
      chunks: ["We", "can", "meet", "at", "five", "cat"],
      answer: ["We", "can", "meet", "at", "five"],
      sentences: "We can meet at five",
    },
    {
      level: "A1",
      chunks: ["The", "door", "is", "now", "open", "dog"],
      answer: ["The", "door", "is", "now", "open"],
      sentences: "The door is now open",
    },
    {
      level: "A1",
      chunks: ["I", "want", "to", "study", "English", "run"],
      answer: ["I", "want", "to", "study", "English"],
      sentences: "I want to study English",
    },
    {
      level: "A1",
      chunks: ["She", "is", "a", "very", "kind", "person", "food"],
      answer: ["She", "is", "a", "very", "kind", "person"],
      sentences: "She is a very kind person",
    },
    {
      level: "A1",
      chunks: ["They", "have", "three", "young", "kids", "cat"],
      answer: ["They", "have", "three", "young", "kids"],
      sentences: "They have three young kids",
    },
    {
      level: "A1",
      chunks: ["He", "eats", "bread", "every", "morning", "dog"],
      answer: ["He", "eats", "bread", "every", "morning"],
      sentences: "He eats bread every morning",
    },
    {
      level: "A1",
      chunks: ["I", "love", "to", "read", "funny", "books", "run"],
      answer: ["I", "love", "to", "read", "funny", "books"],
      sentences: "I love to read funny books",
    },
    {
      level: "A1",
      chunks: ["It", "is", "too", "late", "to", "play", "food"],
      answer: ["It", "is", "too", "late", "to", "play"],
      sentences: "It is too late to play",
    },
    {
      level: "A1",
      chunks: ["She", "writes", "in", "her", "diary", "cat"],
      answer: ["She", "writes", "in", "her", "diary"],
      sentences: "She writes in her diary",
    },
    {
      level: "A1",
      chunks: ["They", "go", "to", "work", "by", "bus", "dog"],
      answer: ["They", "go", "to", "work", "by", "bus"],
      sentences: "They go to work by bus",
    },
    {
      level: "A1",
      chunks: ["He", "listens", "to", "the", "radio", "run"],
      answer: ["He", "listens", "to", "the", "radio"],
      sentences: "He listens to the radio",
    },
    {
      level: "A1",
      chunks: ["I", "need", "a", "pair", "of", "shoes", "food"],
      answer: ["I", "need", "a", "pair", "of", "shoes"],
      sentences: "I need a pair of shoes",
    },
    {
      level: "A1",
      chunks: ["She", "is", "taking", "a", "photo", "cat"],
      answer: ["She", "is", "taking", "a", "photo"],
      sentences: "She is taking a photo",
    },
    {
      level: "A1",
      chunks: ["They", "play", "soccer", "every", "Sunday", "dog"],
      answer: ["They", "play", "soccer", "every", "Sunday"],
      sentences: "They play soccer every Sunday",
    },
    {
      level: "A1",
      chunks: ["He", "has", "a", "cold", "today", "run"],
      answer: ["He", "has", "a", "cold", "today"],
      sentences: "He has a cold today",
    },
    {
      level: "A1",
      chunks: ["I", "am", "cleaning", "my", "room", "food"],
      answer: ["I", "am", "cleaning", "my", "room"],
      sentences: "I am cleaning my room",
    },
    {
      level: "A1",
      chunks: ["She", "speaks", "four", "languages", "well", "cat"],
      answer: ["She", "speaks", "four", "languages", "well"],
      sentences: "She speaks four languages well",
    },
    {
      level: "A1",
      chunks: ["They", "enjoy", "the", "summer", "weather", "dog"],
      answer: ["They", "enjoy", "the", "summer", "weather"],
      sentences: "They enjoy the summer weather",
    },
    {
      level: "A1",
      chunks: ["He", "sits", "on", "the", "soft", "chair", "run"],
      answer: ["He", "sits", "on", "the", "soft", "chair"],
      sentences: "He sits on the soft chair",
    },
    {
      level: "A1",
      chunks: ["I", "can", "fix", "my", "broken", "bike", "food"],
      answer: ["I", "can", "fix", "my", "broken", "bike"],
      sentences: "I can fix my broken bike",
    },
    {
      level: "A1",
      chunks: ["She", "paints", "a", "beautiful", "picture", "cat"],
      answer: ["She", "paints", "a", "beautiful", "picture"],
      sentences: "She paints a beautiful picture",
    },
    {
      level: "A1",
      chunks: ["They", "are", "very", "busy", "today", "dog"],
      answer: ["They", "are", "very", "busy", "today"],
      sentences: "They are very busy today",
    },
    {
      level: "A1",
      chunks: ["He", "helps", "his", "father", "outside", "run"],
      answer: ["He", "helps", "his", "father", "outside"],
      sentences: "He helps his father outside",
    },
    {
      level: "A1",
      chunks: ["I", "forget", "my", "key", "at", "home", "food"],
      answer: ["I", "forget", "my", "key", "at", "home"],
      sentences: "I forget my key at home",
    },
    {
      level: "A1",
      chunks: ["She", "is", "calling", "her", "best", "friend", "cat"],
      answer: ["She", "is", "calling", "her", "best", "friend"],
      sentences: "She is calling her best friend",
    },
    {
      level: "A1",
      chunks: ["They", "arrive", "at", "the", "airport", "early", "dog"],
      answer: ["They", "arrive", "at", "the", "airport", "early"],
      sentences: "They arrive at the airport early",
    },
    {
      level: "A1",
      chunks: ["He", "is", "a", "very", "funny", "man", "run"],
      answer: ["He", "is", "a", "very", "funny", "man"],
      sentences: "He is a very funny man",
    },
    {
      level: "A1",
      chunks: ["I", "drink", "coffee", "without", "any", "sugar", "food"],
      answer: ["I", "drink", "coffee", "without", "any", "sugar"],
      sentences: "I drink coffee without any sugar",
    },
    {
      level: "A1",
      chunks: ["She", "is", "wearing", "her", "red", "dress", "cat"],
      answer: ["She", "is", "wearing", "her", "red", "dress"],
      sentences: "She is wearing her red dress",
    },
    {
      level: "A1",
      chunks: ["They", "like", "to", "go", "to", "parties", "dog"],
      answer: ["They", "like", "to", "go", "to", "parties"],
      sentences: "They like to go to parties",
    },
    {
      level: "A1",
      chunks: ["He", "writes", "a", "letter", "to", "me", "run"],
      answer: ["He", "writes", "a", "letter", "to", "me"],
      sentences: "He writes a letter to me",
    },
    {
      level: "A1",
      chunks: ["I", "visit", "my", "grandparents", "every", "week", "food"],
      answer: ["I", "visit", "my", "grandparents", "every", "week"],
      sentences: "I visit my grandparents every week",
    },
    {
      level: "A1",
      chunks: ["She", "makes", "a", "cake", "for", "lunch", "cat"],
      answer: ["She", "makes", "a", "cake", "for", "lunch"],
      sentences: "She makes a cake for lunch",
    },
    {
      level: "A1",
      chunks: ["They", "are", "very", "happy", "to", "see", "us", "dog"],
      answer: ["They", "are", "very", "happy", "to", "see", "us"],
      sentences: "They are very happy to see us",
    },
    {
      level: "A1",
      chunks: ["He", "is", "playing", "the", "guitar", "now", "run"],
      answer: ["He", "is", "playing", "the", "guitar", "now"],
      sentences: "He is playing the guitar now",
    },
    {
      level: "A1",
      chunks: ["I", "want", "to", "buy", "some", "fruit", "food"],
      answer: ["I", "want", "to", "buy", "some", "fruit"],
      sentences: "I want to buy some fruit",
    },
    {
      level: "A1",
      chunks: ["She", "is", "the", "smartest", "girl", "here", "cat"],
      answer: ["She", "is", "the", "smartest", "girl", "here"],
      sentences: "She is the smartest girl here",
    },
    {
      level: "A1",
      chunks: ["They", "have", "a", "lot", "of", "work", "dog"],
      answer: ["They", "have", "a", "lot", "of", "work"],
      sentences: "They have a lot of work",
    },
    {
      level: "A1",
      chunks: ["He", "can", "jump", "over", "the", "fence", "run"],
      answer: ["He", "can", "jump", "over", "the", "fence"],
      sentences: "He can jump over the fence",
    },
    {
      level: "A1",
      chunks: ["I", "use", "my", "phone", "to", "talk", "food"],
      answer: ["I", "use", "my", "phone", "to", "talk"],
      sentences: "I use my phone to talk",
    },
    {
      level: "A1",
      chunks: ["She", "is", "my", "favorite", "person", "cat"],
      answer: ["She", "is", "my", "favorite", "person"],
      sentences: "She is my favorite person",
    },
    {
      level: "A1",
      chunks: ["They", "wait", "for", "the", "last", "bus", "dog"],
      answer: ["They", "wait", "for", "the", "last", "bus"],
      sentences: "They wait for the last bus",
    },
    {
      level: "A1",
      chunks: ["He", "loses", "his", "wallet", "at", "school", "run"],
      answer: ["He", "loses", "his", "wallet", "at", "school"],
      sentences: "He loses his wallet at school",
    },
    {
      level: "A1",
      chunks: ["I", "change", "my", "shoes", "for", "sports", "food"],
      answer: ["I", "change", "my", "shoes", "for", "sports"],
      sentences: "I change my shoes for sports",
    },
    {
      level: "A1",
      chunks: ["She", "is", "always", "in", "a", "hurry", "cat"],
      answer: ["She", "is", "always", "in", "a", "hurry"],
      sentences: "She is always in a hurry",
    },
    {
      level: "A1",
      chunks: ["They", "are", "ready", "for", "the", "trip", "dog"],
      answer: ["They", "are", "ready", "for", "the", "trip"],
      sentences: "They are ready for the trip",
    },
  ];

  let count = 0;
  for (const item of listeningSeeds) {
    const exists = await prisma.listeningQuestion.findFirst({
      where: { level: item.level, sentences: item.sentences },
    });
    if (!exists) {
      await prisma.listeningQuestion.create({ data: item });
      count++;
    }
  }

  console.log(`✅ ${count} listening questions seeded`);
  return count;
}

module.exports = { seedListening };
